package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"reviewflow/graph/model"
	"reviewflow/graph/resolvers"
)

// CreateSnippet is the resolver for the createSnippet field.
// Saves the snippet synchronously, fires an async AI review, returns immediately.
func (r *mutationResolver) CreateSnippet(ctx context.Context, input model.CreateSnippetInput) (*model.Snippet, error) {
	return resolvers.CreateSnippet(ctx, r.DB, r.AI, input)
}

// AddReview is the resolver for the addReview field.
// Inserts a review, broadcasts ws.MessageReviewAdded to the snippet's room, and
// drops a notification in the snippet author's bell.
func (r *mutationResolver) AddReview(ctx context.Context, snippetID string, input model.AddReviewInput) (*model.Review, error) {
	return resolvers.AddReview(ctx, r.DB, r.Hub, snippetID, input)
}

// Snippet is the resolver for the snippet field.
func (r *queryResolver) Snippet(ctx context.Context, id string) (*model.Snippet, error) {
	return resolvers.GetSnippet(ctx, r.DB, id)
}

// Snippets is the resolver for the snippets field.
func (r *queryResolver) Snippets(ctx context.Context, authorID *string, language *string, limit *int) ([]*model.Snippet, error) {
	return resolvers.ListSnippets(ctx, r.DB, authorID, language, limit)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return resolvers.Me(ctx, r.DB)
}

// AiReview is the resolver for the aiReview field.
// Lazily loads the stored AI review for this snippet (null until generated).
func (r *snippetResolver) AiReview(ctx context.Context, obj *model.Snippet) (*model.AIReview, error) {
	return resolvers.AIReviewForSnippet(ctx, r.DB, obj.ID)
}

// ReviewAdded is the resolver for the reviewAdded field.
//
// Browser clients receive review_added over the WebSocket hub (internal/ws),
// which AddReview publishes to. This GraphQL subscription would be a typed
// alternative for GraphQL-over-WS clients; it remains a stub because the WS hub
// already covers the realtime path the frontend uses.
func (r *subscriptionResolver) ReviewAdded(ctx context.Context, snippetID string) (<-chan *model.Review, error) {
	ch := make(chan *model.Review)
	close(ch)
	return ch, nil
}

// PresenceUpdated is the resolver for the presenceUpdated field.
// Presence is delivered over the WebSocket hub; this GraphQL surface is a stub.
func (r *subscriptionResolver) PresenceUpdated(ctx context.Context, snippetID string) (<-chan *model.PresenceEvent, error) {
	ch := make(chan *model.PresenceEvent)
	close(ch)
	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Snippet returns SnippetResolver implementation.
func (r *Resolver) Snippet() SnippetResolver { return &snippetResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type snippetResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
