// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AIReview struct {
	ID            string    `json:"id"`
	SnippetID     string    `json:"snippetId"`
	Suggestions   []string  `json:"suggestions"`
	Complexity    string    `json:"complexity"`
	RefactorHints []string  `json:"refactorHints"`
	SecurityFlags []string  `json:"securityFlags"`
	QualityScore  int       `json:"qualityScore"`
	Language      string    `json:"language"`
	GeneratedAt   time.Time `json:"generatedAt"`
}

type AddReviewInput struct {
	Body           string  `json:"body"`
	LineNumber     *int    `json:"lineNumber,omitempty"`
	ParentReviewID *string `json:"parentReviewId,omitempty"`
}

type CreateSnippetInput struct {
	Title           string  `json:"title"`
	Language        string  `json:"language"`
	Code            string  `json:"code"`
	PreviousVersion *string `json:"previousVersion,omitempty"`
}

type Mutation struct {
}

type PresenceEvent struct {
	SnippetID string         `json:"snippetId"`
	User      *User          `json:"user"`
	Status    PresenceStatus `json:"status"`
	At        time.Time      `json:"at"`
}

type Query struct {
}

type Review struct {
	ID             string    `json:"id"`
	SnippetID      string    `json:"snippetId"`
	Author         *User     `json:"author"`
	Body           string    `json:"body"`
	LineNumber     *int      `json:"lineNumber,omitempty"`
	ParentReviewID *string   `json:"parentReviewId,omitempty"`
	CreatedAt      time.Time `json:"createdAt"`
}

type Snippet struct {
	ID              string    `json:"id"`
	Title           string    `json:"title"`
	Language        string    `json:"language"`
	Code            string    `json:"code"`
	PreviousVersion *string   `json:"previousVersion,omitempty"`
	Author          *User     `json:"author"`
	Reviews         []*Review `json:"reviews"`
	AiReview        *AIReview `json:"aiReview,omitempty"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

type Subscription struct {
}

type User struct {
	ID             string    `json:"id"`
	GithubUsername string    `json:"githubUsername"`
	AvatarURL      string    `json:"avatarUrl"`
	CreatedAt      time.Time `json:"createdAt"`
}

type PresenceStatus string

const (
	PresenceStatusJoined  PresenceStatus = "JOINED"
	PresenceStatusLeft    PresenceStatus = "LEFT"
	PresenceStatusViewing PresenceStatus = "VIEWING"
)

var AllPresenceStatus = []PresenceStatus{
	PresenceStatusJoined,
	PresenceStatusLeft,
	PresenceStatusViewing,
}

func (e PresenceStatus) IsValid() bool {
	switch e {
	case PresenceStatusJoined, PresenceStatusLeft, PresenceStatusViewing:
		return true
	}
	return false
}

func (e PresenceStatus) String() string {
	return string(e)
}

func (e *PresenceStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PresenceStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PresenceStatus", str)
	}
	return nil
}

func (e PresenceStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PresenceStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PresenceStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
